# Generated by Django 3.0.4 on 2020-04-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=22)),
                ('emp_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_city', to='company.city')),
                ('emp_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_title', to='company.title')),
            ],
        ),
    ]
