# Generated by Django 3.0.4 on 2020-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employ',
            name='emp_city',
        ),
        migrations.RemoveField(
            model_name='employ',
            name='emp_title',
        ),
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='employ',
        ),
        migrations.DeleteModel(
            name='title',
        ),
    ]
